# Generated by Django 2.0.9 on 2019-02-25 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', 'January / March'), ('2', 'April / June'), ('3', 'July / September'), ('4', 'October / December')], default='1', max_length=1)),
                ('is_active', models.BooleanField(default='False')),
                ('total_budget', models.IntegerField()),
                ('remaining_budget', models.IntegerField(blank=True, null=True)),
                ('vote_list', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_list', models.CharField(blank=True, max_length=255, null=True)),
                ('voters_list', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.CharField(blank=True, max_length=255, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Project'),
        ),
        migrations.AddField(
            model_name='process',
            name='voters',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.User'),
        ),
    ]
